# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f4f493c69099f2ff8a18f8092049630c83ddadf552aee435e6c8f8a7d1108913d08b5ad803929c1f952594b2c0ad97340b423203c74026c3eff7cc27ce53c0a

test:
  secret_key_base: 06d8d20b5b8e3d18e390cbb3dbc6a7d94033df029e66731a095e3bd708364409a8497e2f3ee93906a9eba3ab4afe9d3461277b9672bb55ef7a3336a1484d87bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
